json.id entry_rule.id
json.account_id entry_rule.account_id
json.kanban_board_id entry_rule.kanban_board_id
json.kanban_stage_id entry_rule.kanban_stage_id
json.name entry_rule.name
json.active entry_rule.active?
json.all_inboxes entry_rule.all_inboxes?
json.position entry_rule.position
json.conditions entry_rule.conditions
json.inbox_ids entry_rule.kanban_board_entry_rule_inboxes.map(&:inbox_id).sort
json.created_at entry_rule.created_at.to_i
json.updated_at entry_rule.updated_at.to_i
